//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicalServiceManagement1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerCenter
    {
        public int ServiceCenterID { get; set; }
        public string ServiceCenterName { get; set; }
        public string AppBookDate { get; set; }
        public string VehicalType { get; set; }
        public string VehicalModel { get; set; }
    }
}
